export const BASE_BMKG_WEATHER_URL =
  'https://data.bmkg.go.id/DataMKG/MEWS/DigitalForecast/';

export const XML_DATA = [
  'DigitalForecast-Aceh.xml',
  'DigitalForecast-Bali.xml',
  'DigitalForecast-BangkaBelitung.xml',
  'DigitalForecast-Banten.xml',
  'DigitalForecast-Bengkulu.xml',
  'DigitalForecast-DIYogyakarta.xml',
  'DigitalForecast-DKIJakarta.xml',
  'DigitalForecast-Gorontalo.xml',
  'DigitalForecast-Jambi.xml',
  'DigitalForecast-JawaBarat.xml',
  'DigitalForecast-JawaTengah.xml',
  'DigitalForecast-JawaTimur.xml',
  'DigitalForecast-KalimantanBarat.xml',
  'DigitalForecast-KalimantanSelatan.xml',
  'DigitalForecast-KalimantanTengah.xml',
  'DigitalForecast-KalimantanTimur.xml',
  'DigitalForecast-KalimantanUtara.xml',
  'DigitalForecast-KepulauanRiau.xml',
  'DigitalForecast-Lampung.xml',
  'DigitalForecast-Maluku.xml',
  'DigitalForecast-MalukuUtara.xml',
  'DigitalForecast-NusaTenggaraBarat.xml',
  'DigitalForecast-NusaTenggaraTimur.xml',
  'DigitalForecast-Papua.xml',
  'DigitalForecast-PapuaBarat.xml',
  'DigitalForecast-Riau.xml',
  'DigitalForecast-SulawesiBarat.xml',
  'DigitalForecast-SulawesiSelatan.xml',
  'DigitalForecast-SulawesiTengah.xml',
  'DigitalForecast-SulawesiTenggara.xml',
  'DigitalForecast-SulawesiUtara.xml',
  'DigitalForecast-SumateraBarat.xml',
  'DigitalForecast-SumateraSelatan.xml',
  'DigitalForecast-SumateraUtara.xml',
  // 'DigitalForecast-Indonesia.xml',
];
